### ISSUE TITLE
HSA_STATUS_ERROR_VARIABLE_ALREADY_DEFINED

### ISSUE THREAD

**Issue by ams-cs** [RadeonOpenCompute/ROCR-Runtime#49] opened 2018-12-20 12:11 UTC
If a HSACO binary has been linked from multiple object files, and two of those objects happen to have a *local* symbol with the same name, then the loader will reject the code object with HSA_STATUS_ERROR_VARIABLE_ALREADY_DEFINED.

This behaviour is a problem because it's common for runtime libraries to include common names in many files, and because at least GCC uses the same names for labels associated with switch conversion and the like. (The recently released [CodeBench Lite compiler for GCN](https://www.mentor.com/embedded-software/sourcery-tools/sourcery-codebench/editions/lite-edition/) uses name mangling to work around this, for now, but that's not an acceptable solution for upstream GCC.)

I found the issues in GCC, but this testcase, [loaderbug.zip](https://github.com/RadeonOpenCompute/ROCR-Runtime/files/2698747/loaderbug.zip), demonstrates the problem using only tools included with a ROCM install. I've tested it with the latest Ubuntu packages (hsa-rocr-dev: 1.1.9-45-ge88639f).

Please run `./build.sh`, substituting the correct `-mcpu` flag for your system, then run `./a.out` to demonstrate the error.

The testcase does nothing interesting, but there are two instances of `var` which should not conflict, but do. If you exclude the second object file from the link command then the testcase runs to completion with no errors.

The `launch.c` code is derived from the old "vector_copy" sample code, and does nothing interesting; I include it only to make the testcase easier to try.

**Comment by scott-linder** [comment] 2019-01-08 22:52
There was some discussion in another thread already, so for context I'll try to summarize here the current status and questions I have (with some of this also representing others from AMD):

Currently our loader ignores the .dynsym, looking only in the .symtab. The example bug you point out is a direct consequence of this, and it is our intention to fix the bug in the loader by having it ignore the .symtab and look in the .dynsym.

One consequence of this is that your use of `--pie` (which does not produce any symbols in the .dynsym, as it expects the symbols will not be needed at runtime for e.g. preemption) will also cause your example to fail, even with a correct loader. Instead, `-shared` will produce a shared object with a populated .dynsym.

You are concerned about "dynamic symbols, GOT relocations, PIC registers" which `-shared` implies, but:

- The runtimes which depend on the loader require dynamic symbols in order to function. For OpenCL at least we implement determining the address of the kernel descriptor (needed for enqueueing the kernel) via the .dynsym (or the .symtab in the existing loader).
- Even with `-shared` the GOT relocations can be elided as an optimisation through visibility/preemptibility controls. Concurrent with the change to the loader we will be updating the compiler to ensure this occurs in the default case, while still allowing the user to override symbol visibility. There are changes required in LLVM/Clang to make this possible, and I suspect that may be true of GCC as well, but we have to address this in order to produce a loadable code object with only the minimum required relocations.
- I believe we do wish to generate PIC code, and my understanding was that PIE is also PIC; if you can expand more on this I can see if we will be able to resolve this as part of the compiler changes.

I think we should discuss any concerns you have with `-shared` vs. `--pie` that I don't address above, or any misunderstandings I still have. As it stands, our fix to the original issue reported here exposes an incompatibility with `--pie` which we will have to understand and resolve.

**Comment by ams-cs** [comment] 2019-01-09 10:14
Firstly, I don't believe this bug needs to have anything to do with `.dynsym`. The extract from readelf, below, shows that the "duplicate" symbols are both marked `LOCAL`, and therefore do not conflict. This executable, PIE or otherwise, should be able to load on any architecture (assuming the obvious adjustments to other content). If you're planning to use `.dynsym` exclusively (and mandate `-shared`) then this doesn't so much fix the issue as side-step it.

```
Symbol table '.symtab' contains 5 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000002000     4 OBJECT  LOCAL  DEFAULT    7 var
     2: 0000000000002010     4 OBJECT  LOCAL  DEFAULT    7 var
     3: 0000000000003000     0 NOTYPE  LOCAL  HIDDEN     8 _DYNAMIC
     4: 0000000000001000   260 IFUNC   GLOBAL DEFAULT    6 main
```

Secondly, please, please, *please* don't change the loader in such a way that it breaks existing toolchains or binaries. That would be extremely painful.

----

So, please fix it such that you only extract global symbols from `.symtab`. Or, if you have a toolchain that expects that local symbols can be queried via the API, then simply suppress the error condition for local symbols.

By all means add support for `.dynsym`, but please do so in a backwards compatible way.

Thanks

**Comment by skeelyamd** [comment] 2019-06-05 01:02
@scott-linder, is this issue still work in progress?

**Comment by scott-linder** [comment] 2019-06-06 18:50
@skeelyamd I believe the issue is resolved for the current code object v2 loader. It was updated to ignore the local symbols. If @ams-cs doesn't have any other concerns I think we can close this ticket.

**Comment by skeelyamd** [comment] 2019-06-06 19:59
@ams-cs, please reopen if the issue is still observed.

**Closed by skeelyamd** 2019-06-06 19:59 UTC

**Comment by ams-cs** [comment] 2019-06-07 08:47
I can confirm that I no longer see any problems with the latest updates.
Thanks all. :-)
